# Required packages for nagios on Ubuntu 20.04
required_packages:
  - autoconf
  - gcc
  - libc6
  - make
  - wget
  - unzip
  - apache2
  - php
  - libapache2-mod-php
  - libgd-dev
  - openssl
  - libssl-dev
  - libmcrypt-dev
  - bc
  - gawk 
  - dc
  - build-essential
  - snmp
  - libnet-snmp-perl
  - gettext