- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Build index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes